### ISSUE TITLE
Found an old copy of the Darcs repo with full history

### ISSUE THREAD

**Issue by hraban** [hraban/metacopy#1]
See "https://github.com/hraban/metacopy". It contains older revisions as well as more recent versions.

If you'd like to clone it and host it on your repo please feel free and I'll go ahead and delete my fork.

**Comment by gwkkwg** [comment]
Hi there,

I am no longer maintaining this library (or any other) or working in software 😀. I can give you commit rights if you’d like (and I can remember how!).

**Comment by hraban** [comment]
God bless on your journey wherever you go 🌌

Sure thing, I'll take on maintenance of this extremely stable library :)

**Comment by phoe** [comment]
https://github.com/gwkkwg/metacopy/settings/access should be the link for giving repository commit rights. No idea if just commit access will be enough for a force push though, since a force push would mean rewriting the current Git history with "new" parent commits.

**Comment by gwkkwg** [comment]
Thanks!
